# Generated by Django 4.2 on 2023-07-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizations',
            old_name='lower',
            new_name='dimensions',
        ),
        migrations.RemoveField(
            model_name='customizations',
            name='upper',
        ),
    ]
